---
    php_ppa: php5-5.6
    doc_root: /vagrant
    sys_packages: ["vim","git"]
    dist: precise
    php_packages: ["php5-curl","php5-gd","php5-mcrypt","php5-memcached","php5-mysql","php5-xdebug","php5-cli","php-pear"]
    pecl_packages: []
